# Generated by Django 4.1.4 on 2023-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(max_length=56, null=True)),
                ('city', models.CharField(max_length=56, null=True)),
                ('dob', models.DateField(null=True)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
            ],
        ),
    ]
